package com.qhit.gr3.xhq.bean;

import java.util.HashSet;
import java.util.Set;

// Generated 2017-12-22 19:27:30 by Hibernate Tools 3.4.0.CR1

/**
 * TDept generated by hbm2java
 */
public class TDept implements java.io.Serializable {

	private int id;
	private String dname;
	
	//多对�?
	private Set<TUser> users=new HashSet<TUser>();
	public TDept() {
	}

	public TDept(int id, String dname) {
		this.id = id;
		this.dname = dname;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDname() {
		return this.dname;
	}

	public void setDname(String dname) {
		this.dname = dname;
	}

	public Set<TUser> getUsers() {
		return users;
	}

	public void setUsers(Set<TUser> users) {
		this.users = users;
	}

	@Override
	public String toString() {
		return "TDept [id=" + id + ", dname=" + dname + "]";
	}
	
	
}
