package com.qhit.gr3.xhq.bean;
// Generated 2017-12-22 19:27:30 by Hibernate Tools 3.4.0.CR1

/**
 * TUser generated by hbm2java
 */
public class TUser implements java.io.Serializable {

	private int uid;
	private String uname;
	private int uage;
	private String birthday;
	private Integer deptid;
	//�?对多
	private TDept dept;
	
	public TUser() {
	}

	public TUser(int uid, String uname, int uage, String birthday) {
		this.uid = uid;
		this.uname = uname;
		this.uage = uage;
		this.birthday = birthday;
	}

	public TUser(int uid, String uname, int uage, String birthday, Integer deptid) {
		this.uid = uid;
		this.uname = uname;
		this.uage = uage;
		this.birthday = birthday;
		this.deptid = deptid;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public int getUage() {
		return this.uage;
	}

	public void setUage(int uage) {
		this.uage = uage;
	}

	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	public Integer getDeptid() {
		return this.deptid;
	}

	public void setDeptid(Integer deptid) {
		this.deptid = deptid;
	}

	public TDept getDept() {
		return dept;
	}

	public void setDept(TDept dept) {
		this.dept = dept;
	}

	@Override
	public String toString() {
		return "TUser [uid=" + uid + ", uname=" + uname + ", uage=" + uage + ", birthday=" + birthday + ", deptid="
				+ deptid + "]";
	}
	
}
