package com.qhit.lh.gr3.xhq.bean;

import java.util.HashSet;
import java.util.Set;

// Generated 2017-12-20 20:21:49 by Hibernate Tools 3.4.0.CR1

/**
 * TRole generated by hbm2java
 */
public class TRole implements java.io.Serializable {

	private int rid;
	private String rname;
	private String rmsg;
	
	private Set<TUserinfo> infos=new HashSet<TUserinfo>();
	public TRole() {
	}

	public TRole(int rid, String rname, String rmsg) {
		this.rid = rid;
		this.rname = rname;
		this.rmsg = rmsg;
	}

	public TRole(int rid, String rname, String rmsg, Set<TUserinfo> infos) {
		super();
		this.rid = rid;
		this.rname = rname;
		this.rmsg = rmsg;
		this.infos = infos;
	}

	public int getRid() {
		return this.rid;
	}

	public void setRid(int rid) {
		this.rid = rid;
	}

	public String getRname() {
		return this.rname;
	}

	public void setRname(String rname) {
		this.rname = rname;
	}

	public String getRmsg() {
		return this.rmsg;
	}

	public void setRmsg(String rmsg) {
		this.rmsg = rmsg;
	}

	public Set<TUserinfo> getInfos() {
		return infos;
	}

	public void setInfos(Set<TUserinfo> infos) {
		this.infos = infos;
	}
	
	
}
