package com.grsb.xhq.bean;
// Generated 2017-12-16 21:51:47 by Hibernate Tools 5.2.6.Final

/**
 * TLogin generated by hbm2java
 */
public class TLogin implements java.io.Serializable {

	private Integer uid;
	private String uname;
	private String upwd;

	public TLogin() {
	}

	public TLogin(String uname, String upwd) {
		this.uname = uname;
		this.upwd = upwd;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getUpwd() {
		return this.upwd;
	}

	public void setUpwd(String upwd) {
		this.upwd = upwd;
	}

}
