package com.qhit.lh.gr3.xhq.bean;
// Generated 2017-12-14 20:20:09 by Hibernate Tools 5.2.6.Final

/**
 * TInfo generated by hbm2java
 */
public class TInfo implements java.io.Serializable {

	private int id;
	private String name;
	private String account;
	private String pwd;
	//1-1换脸员工对象
	private TUser tUser;
	public TInfo() {
	}

	public TInfo(int id, String name, String account, String pwd) {
		this.id = id;
		this.name = name;
		this.account = account;
		this.pwd = pwd;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}
	
	public TUser gettUser() {
		return tUser;
	}

	public void settUser(TUser tUser) {
		this.tUser = tUser;
	}

	@Override
	public String toString() {
		return "TInfo [id=" + id + ", name=" + name + ", account=" + account + ", pwd=" + pwd + "]";
	}

}
