package com.qhit.lh.gr3.xhq.bean;
// Generated 2017-12-14 20:20:09 by Hibernate Tools 5.2.6.Final

/**
 * TUser generated by hbm2java
 */
public class TUser implements java.io.Serializable {

	private Integer uid;
	private String uname;
	private int uage;
	private String birthday;
	private Integer deptid;
	//1-1关联账号对象
	private TInfo info;
	//n-1关联部门对象
	private TDept dept;
	
	public TUser() {
	}
	
	
	public TUser(String uname, int uage, String birthday, Integer deptid, TInfo info, TDept dept) {
		super();
		this.uname = uname;
		this.uage = uage;
		this.birthday = birthday;
		this.deptid = deptid;
		this.info = info;
		this.dept = dept;
	}


	public Integer getUid() {
		return uid;
	}


	public void setUid(Integer uid) {
		this.uid = uid;
	}


	public String getUname() {
		return uname;
	}


	public void setUname(String uname) {
		this.uname = uname;
	}


	public int getUage() {
		return uage;
	}


	public void setUage(int uage) {
		this.uage = uage;
	}


	public String getBirthday() {
		return birthday;
	}


	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}


	public Integer getDeptid() {
		return deptid;
	}


	public void setDeptid(Integer deptid) {
		this.deptid = deptid;
	}


	public TInfo getInfo() {
		return info;
	}


	public void setInfo(TInfo info) {
		this.info = info;
	}


	public TDept getDept() {
		return dept;
	}


	public void setDept(TDept dept) {
		this.dept = dept;
	}


	@Override
	public String toString() {
		return "TUser [uid=" + uid + ", uname=" + uname + ", uage=" + uage + ", birthday=" + birthday + ", deptid="
				+ deptid + ", info=" + info + ", dept=" + dept + "]";
	}
	
}
